repomaker/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.views.i18n import JavaScriptCatalog
from django_js_reverse.views import urls_js

from repomaker.models import S3Storage, SshStorage, GitStorage
from repomaker.views import media_serve
from repomaker.views.apk import ApkUploadView, ApkPointerDeleteView
from repomaker.views.app import AppDetailView, AppDeleteView, AppEditView, \
    AppTranslationCreateView, AppFeatureGraphicDeleteView
from repomaker.views.gitstorage import GitStorageCreate, GitStorageUpdate, GitStorageDetail, \
    GitStorageDelete
from repomaker.views.remoterepository import RemoteRepositoryCreateView, AppRemoteAddView, \
    RemoteAppImportView, RemoteAppImportViewScreenshots
from repomaker.views.repository import RepositoryCreateView, RepositoryView, RepositoryUpdateView, \
    RepositoryDeleteView, RepositoryListView
from repomaker.views.s3storage import S3StorageCreate, S3StorageDetail, S3StorageUpdate, \
    S3StorageDelete
from repomaker.views.screenshot import ScreenshotDeleteView
from repomaker.views.sshstorage import SshStorageCreate, SshStorageUpdate, SshStorageDetail, \
    SshStorageDelete
from repomaker.views.storage import StorageAddView
from . import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^jsreverse/$', urls_js, name='js_reverse'),
    url(r'^%s(?P<path>.*)$' % settings.MEDIA_URL[1:], media_serve,
        {'document_root': settings.MEDIA_ROOT}, name='media'),

    # JavaScript Internationalisation
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(packages=['repomaker']), name='javascript-catalog'),

    # Repo
    url(r'^$', RepositoryListView.as_view(), name='index'),
    url(r'^add$', RepositoryCreateView.as_view(), name='add_repo'),
    url(r'^(?P<repo_id>[0-9]+)/$', RepositoryView.as_view(), name='repo'),
    url(r'^(?P<repo_id>[0-9]+)/edit/$', RepositoryUpdateView.as_view(),
        name='edit_repo'),
    url(r'^(?P<repo_id>[0-9]+)/delete/$', RepositoryDeleteView.as_view(),
        name='delete_repo'),

    # Remote Repo
    url(r'^remote/add$', RemoteRepositoryCreateView.as_view(), name='add_remote_repo'),
    url(r'^remote/(?P<remote_repo_id>[0-9]+)/update/$', views.remote_update, name='remote_update'),

    # App
    url(r'^(?P<repo_id>[0-9]+)/app/add/$', AppRemoteAddView.as_view(), name='add_app'),
    url(r'^(?P<repo_id>[0-9]+)/remote-app/(?P<remote_repo_id>[0-9]+)/add/$',
        AppRemoteAddView.as_view(), name='add_app'),
    url(r'^(?P<repo_id>[0-9]+)/remote-app/add/category/(?P<category_id>[0-9]+)/$',
        AppRemoteAddView.as_view(), name='add_app_with_category'),
    url(r'^(?P<repo_id>[0-9]+)/remote-app/(?P<remote_repo_id>[0-9]+)/add/' +
        r'category/(?P<category_id>[0-9]+)/$',
        AppRemoteAddView.as_view(), name='add_app_with_category'),
    # Remote App Details
    url(r'^(?P<repo_id>[0-9]+)/remote-app/(?P<remote_repo_id>[0-9]+)/(?P<app_id>[0-9]+)' +
        r'/lang/(?P<lang>[a-zA-Z_-]+)/$',
        RemoteAppImportView.as_view(), name='add_remote_app'),
    url(r'^(?P<repo_id>[0-9]+)/remote-app/(?P<remote_repo_id>[0-9]+)/(?P<app_id>[0-9]+)' +
        r'/lang/(?P<lang>[a-zA-Z_-]+)/screenshots/$',
        RemoteAppImportViewScreenshots.as_view(), name='add_remote_app_screenshots'),
    # App Detail and Edit
    url(r'^(?P<repo_id>[0-9]+)/app/(?P<app_id>[0-9]+)/$', AppDetailView.as_view(), name='app'),
    url(r'^(?P<repo_id>[0-9]+)/app/(?P<app_id>[0-9]+)/lang/(?P<lang>[a-zA-Z_-]+)/$',
        AppDetailView.as_view(), name='app'),
    url(r'^(?P<repo_id>[0-9]+)/app/(?P<app_id>[0-9]+)/lang/(?P<lang>[a-zA-Z_-]+)/edit/$',
        AppEditView.as_view(), name='app_edit'),
    url(r'^(?P<repo_id>[0-9]+)/app/(?P<app_id>[0-9]+)/add/lang/$',
        AppTranslationCreateView.as_view(), name='app_add_lang'),
    # App Delete
    url(r'^(?P<repo_id>[0-9]+)/app/(?P<app_id>[0-9]+)/delete/$', AppDeleteView.as_view(),
        name='delete_app'),
    # Feature Graphic Delete
    url(r'^(?P<repo_id>[0-9]+)/app/(?P<app_id>[0-9]+)/feature_graphic/delete/$',
        AppFeatureGraphicDeleteView.as_view(), name='delete_feature_graphic'),

    # App Screenshots
    url(r'^(?P<repo_id>[0-9]+)/app/(?P<app_id>[0-9]+)/screenshot/(?P<s_id>[0-9]+)/delete/$',
        ScreenshotDeleteView.as_view(), name='screenshot_delete'),

    # Apks
    url(r'^(?P<repo_id>[0-9]+)/app/apk/upload/$', ApkUploadView.as_view(), name='apk_upload'),
    url(r'^(?P<repo_id>[0-9]+)/app/(?P<app_id>[0-9]+)/apk/(?P<pk>[0-9]+)/delete/$',
        ApkPointerDeleteView.as_view(), name='apk_delete'),

    # Repo Operations
    url(r'^(?P<repo_id>[0-9]+)/update/$$', views.update, name='update'),
    url(r'^(?P<repo_id>[0-9]+)/publish/$$', views.publish, name='publish'),

    # Storages
    url(r'^(?P<repo_id>[0-9]+)/storage/add/$',
        StorageAddView.as_view(), name='storage_add'),

    # S3 Storage
    url(r'^(?P<repo_id>[0-9]+)/storage/s3/add/$',
        S3StorageCreate.as_view(), name=S3Storage.add_url_name),
    url(r'^(?P<repo_id>[0-9]+)/storage/s3/(?P<pk>[0-9]+)/$',
        S3StorageDetail.as_view(), name=S3Storage.detail_url_name),
    url(r'^(?P<repo_id>[0-9]+)/storage/s3/(?P<pk>[0-9]+)/edit/$',
        S3StorageUpdate.as_view(), name=S3Storage.edit_url_name),
    url(r'^(?P<repo_id>[0-9]+)/storage/s3/(?P<pk>[0-9]+)/delete/$',
        S3StorageDelete.as_view(), name=S3Storage.delete_url_name),

    # SSH Storage
    url(r'^(?P<repo_id>[0-9]+)/storage/ssh/add/$',
        SshStorageCreate.as_view(), name=SshStorage.add_url_name),
    url(r'^(?P<repo_id>[0-9]+)/storage/ssh/(?P<pk>[0-9]+)/$',
        SshStorageDetail.as_view(), name=SshStorage.detail_url_name),
    url(r'^(?P<repo_id>[0-9]+)/storage/ssh/(?P<pk>[0-9]+)/edit/$',
        SshStorageUpdate.as_view(), name=SshStorage.edit_url_name),
    url(r'^(?P<repo_id>[0-9]+)/storage/ssh/(?P<pk>[0-9]+)/delete/$',
        SshStorageDelete.as_view(), name=SshStorage.delete_url_name),

    # Git Storage
    url(r'^(?P<repo_id>[0-9]+)/storage/git/add/$',
        GitStorageCreate.as_view(), name=GitStorage.add_url_name),
    url(r'^(?P<repo_id>[0-9]+)/storage/git/(?P<pk>[0-9]+)/$',
        GitStorageDetail.as_view(), name=GitStorage.detail_url_name),
    url(r'^(?P<repo_id>[0-9]+)/storage/git/(?P<pk>[0-9]+)/edit/$',
        GitStorageUpdate.as_view(), name=GitStorage.edit_url_name),
    url(r'^(?P<repo_id>[0-9]+)/storage/git/(?P<pk>[0-9]+)/delete/$',
        GitStorageDelete.as_view(), name=GitStorage.delete_url_name),
]

if not settings.SINGLE_USER_MODE:
    urlpatterns += [
        url(r'^accounts/', include('allauth.urls')),
    ]

repomaker/models/apk.py
import fdroidserver
import hashlib
import logging
import os
import zipfile
from datetime import datetime
from io import BytesIO

import magic  # this is python-magic in requirements.txt
import requests
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models.signals import post_delete, pre_delete
from django.dispatch import receiver
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

from repomaker import tasks
from repomaker.models.repository import AbstractRepository
from repomaker.storage import get_apk_file_path, RepoStorage
from .apkpointer import ApkPointer, RemoteApkPointer
from .app import IMAGE, VIDEO, AUDIO, DOCUMENT, BOOK, APK


class Apk(models.Model):
    package_id = models.CharField(max_length=255, blank=True)
    file = models.FileField(upload_to=get_apk_file_path, storage=RepoStorage())
    version_name = models.CharField(max_length=128, blank=True)
    version_code = models.PositiveIntegerField(default=0)
    size = models.PositiveIntegerField(default=0)
    signature = models.CharField(max_length=512, blank=True, null=True)
    hash = models.CharField(max_length=512, blank=True)
    hash_type = models.CharField(max_length=32, blank=True)
    added_date = models.DateTimeField(default=timezone.now)
    is_downloading = models.BooleanField(default=False)

    def __str__(self):
        return self.package_id + " " + str(self.version_code) + " " + self.file.name

    def download_async(self, url):
        """
        Downloads the APK file asynchronously if it is still missing.
        """
        if not self.file:
            tasks.download_apk(self.pk, url)

    def download(self, url):
        """
        Starts a blocking download of the APK file if it is still missing
        and then saves it.

        This also updates all pointers and links/copies the file to them.
        """
        if self.file:
            return

        # download and store file
        file_name = url.rsplit('/', 1)[-1]
        r = requests.get(url, timeout=60)
        if r.status_code != requests.codes.ok:
            # TODO delete self and ApkPointer when this fails permanently
            r.raise_for_status()
        self.file.save(file_name, BytesIO(r.content), save=True)

        # initialize the APK and delete it if there was a problem
        try:
            apk = self.initialize()
        except ValidationError as e:
            logging.warning('Deleting invalid APK file: %s', e)
            ApkPointer.objects.filter(apk=self).all().delete()
            RemoteApkPointer.objects.filter(apk=self).all().delete()
            self.delete()
            return

        # update apk pointers
        pointers = ApkPointer.objects.filter(apk=apk).all()
        for pointer in pointers:
            pointer.link_file_from_apk()
            pointer.repo.update_async()

    def initialize(self, repo=None, app=None):
        """
        Initializes this object based on information retrieved from self.file.

        :param repo: If a Repository is passed here, an ApkPointer (and if needed an App)
                     are created as well.
        :param app: If an App is passed here, the Apk needs to be an update for this app,
                    otherwise a ValidationError will be raised.
        :raises: ValidationError if Apk can not be initialized. Delete it, if you get this error!
        :return: An instance of this Apk objects or a different one if it existed already
        """
        if not self.file:
            raise RuntimeError('Trying to initialize an Apk without file')

        ext = os.path.splitext(self.file.name)[1]
        if ext == '.apk':
            try:
                repo_file = self._get_info_from_apk()
            except fdroidserver.exception.BuildException as e:
                raise ValidationError(e)
            except zipfile.BadZipFile as e:
                raise ValidationError(e)
        else:
            repo_file = self._get_info_from_file()

        if app is not None and app.package_id != repo_file['packageName']:
            raise ValidationError(_('This file is not an update for %s') % app.package_id)

        apk_set = Apk.objects.filter(package_id=repo_file['packageName'], hash=repo_file['hash'])
        if not apk_set.exists():
            self.apply_json_package_info(repo_file)
            self.save()
            apk = self
        elif apk_set.count() == 1 and self == apk_set[0]:
            # we are initializing a new APK from a remote repo,
            # so don't override APK info with local scanning data
            apk = self
        elif apk_set.count() == 1:
            logging.info("Existing Apk found, trying to reuse...")
            apk = apk_set[0]
            if not apk.file:
                apk.file = self.file
                apk.save()
                self.file = None
            self.delete()
        else:
            raise RuntimeError('More than one APK with package ID %s' % repo_file['packageName'])

        if repo is not None:
            if ApkPointer.objects.filter(apk=apk, repo=repo).exists():
                raise ValidationError(_('This APK already exists in the current repo.'))
            pointer = ApkPointer(apk=apk, repo=repo)
            pointer.initialize(repo_file)  # also saves the pointer

        return apk

    def _get_info_from_apk(self):
        """
        Scans the APK file and returns a dictionary of information.
        It also extracts icons and stores them in the repository on disk.

        :return: A dict of APK information or None
        """
        AbstractRepository().get_config()

        # Verify that the signature is correct
        if not fdroidserver.verify_apk_signature(self.file.path):
            raise ValidationError(_('Invalid APK signature'))

        # scan APK and extract information about it
        try:
            repo_file = fdroidserver.scan_apk(self.file.path)
            repo_file['type'] = APK
        except fdroidserver.exception.BuildException as e:
            raise ValidationError(e)

        if 'packageName' not in repo_file:
            raise ValidationError(_('Invalid APK.'))

        return repo_file

    def _get_info_from_file(self):
        repo_file = {
            'sig': None,
            'hash': sha256sum(self.file.path),
            'hashType': 'sha256',
            'size': self.file.size,
            'type': self._get_type()
        }
        file_name = os.path.basename(self.file.name)
        match = fdroidserver.common.STANDARD_FILE_NAME_REGEX.match(file_name)
        if match:
            repo_file['packageName'] = match.group(1)
            repo_file['versionName'] = match.group(2)
            repo_file['versionCode'] = int(match.group(2))
        else:
            repo_file['packageName'] = os.path.splitext(file_name)[0]
            repo_file['versionName'] = datetime.now().strftime('%Y-%m-%d')
            repo_file['versionCode'] = int(datetime.now().timestamp())
        repo_file['name'] = repo_file['packageName']

        return repo_file

    def _get_type(self):
        """
        Retrieves the file's type as str with mime-type checking if known to not be an APK.
        If you need extra file-types, please make sure to add them safely(!) here.
        :raises: ValidationError if doesn't match type on white-list.
        """
        ext = os.path.splitext(self.file.name)[1]
        # exclude dangerous extensions right from the beginning
        if ext.startswith('.php') or ext.startswith('.py') or ext == '.pl' or ext == '.cgi' or \
                ext == '.js' or ext == '.html':
            raise ValidationError(_('Unsupported File Type'))
        # allow a white-list of mime-types
        mime = magic.from_file(self.file.path, mime=True)
        mime_start = mime.split('/', 1)[0]
        if mime_start == 'image':
            return IMAGE
        if mime_start == 'video':
            return VIDEO
        if mime_start == 'audio':
            return AUDIO
        if mime == 'application/epub+zip':
            return BOOK
        if mime == 'application/pdf' or mime.startswith('application/vnd.oasis.opendocument') \
                or ext == '.docx' or ext == '.txt':
            return DOCUMENT
        raise ValidationError(_('Unsupported File Type'))

    def apply_json_package_info(self, package_info):
        """
        Saves package information from index v1 JSON to a fresh Apk object.

        Attention: This does not save the object.
        """
        if self.package_id:
            raise RuntimeError('Trying to apply information to an initialized Apk object.')
        self.package_id = package_info['packageName']
        self.version_name = package_info['versionName']
        self.size = package_info['size']
        self.hash = package_info['hash']
        self.hash_type = package_info['hashType']
        if 'added' in package_info:
            self.added_date = datetime.fromtimestamp(package_info['added'] / 1000, timezone.utc)
        if 'versionCode' in package_info:
            self.version_code = package_info['versionCode']
        if 'sig' in package_info:
            self.signature = package_info['sig']

    def delete_if_no_pointers(self):
        apk_pointers_exist = ApkPointer.objects.filter(apk=self).exists()
        remote_apk_pointers_exist = RemoteApkPointer.objects.filter(apk=self).exists()
        if not apk_pointers_exist and not remote_apk_pointers_exist:
            self.delete()


@receiver(pre_delete, sender=Apk)
def apk_pre_delete_handler(**kwargs):
    apk = kwargs['instance']
    # delete pointers first, so they can still access APK information when cleaning up
    ApkPointer.objects.filter(apk=apk).delete()
    RemoteApkPointer.objects.filter(apk=apk).delete()


@receiver(post_delete, sender=Apk)
def apk_post_delete_handler(**kwargs):
    apk = kwargs['instance']
    if apk.file:
        logging.info("Deleting APK: %s", apk.file.name)

maker/templates/maker/repo/index/apps.html
{% load i18n %}
<div class="rm-grid--center mdl-grid mdl-cell--9-col rm-grid--full-width">
	{% if request.POST.search or apps.count >= 10 %}
	<div class="rm-repo-apps-header mdl-cell mdl-cell--12-col">
		<div class="rm-repo-apps-header-search">
			<a href="#" onclick="toggleSearch()" class="rm-repo-apps-header-search-icon">
				<i class="material-icons">search</i>
			</a>
			<div id="rm-repo-apps-header-search-input"
				 class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label rm-form">
				<form action="" method="post">
					{% csrf_token %}
					<label for="id_search" class="mdl-textfield__label">
						{% trans 'Search for apps in your repository' %}
					</label>
					<input type="text" name="search" id="id_search" class="mdl-textfield__input" value="{{ request.POST.search }}">
				</form>
			</div>
		</div>
	</div>
	{% endif %}
	{% if apps %}
	<div class="rm-repo-apps-add mdl-cell mdl-cell--6-col">
		<div class="rm-repo-apps-add-locally">
			<!-- TODO: Make this a drag and drop area -->
			<div class="rm-repo-apps-empty-add-title">
				<i class="rm-repo-apps-empty-add-icon material-icons">file_upload</i>
				{% trans 'Add .apk files' %}
			</div>
			<!-- TODO: Make this translatable properly -->
			<!--
			<div class="rm-repo-apps-empty-add-description-first">
				{% trans 'Drag and drop .apk, .pdf, .epub, videos, photos or music files' %}
			</div>
			-->
			<div class="rm-repo-apps-empty-add-description-second rm-form">
				<!--{% trans 'or' %}-->
				<form action="{% url 'apk_upload' repo.id %}" enctype="multipart/form-data" method="post">
					{% csrf_token %}
					<label for="id_file" class="rm-repo-apps-empty-add-upload-browse">
						{% trans 'browse to upload' %}
					</label>
					<p>{{ form.file }}</p>
					<button type="submit" class="rm-button--blue mdl-button mdl-js-button">
						{% trans 'Add' %}
					</button>
				</form>
			</div>
		</div>
		<a href="{% url 'add_app' repo.id %}" class="rm-repo-apps-add-remotely">
			<i class="rm-repo-apps-empty-empty-icon material-icons">explore</i>
			<div class="rm-repo-apps-add-remotely-title">
				{% trans 'add from repos' %}
			</div>
		</a>
	</div>
	{% for app in apps %}
		{% url 'app' repo.id app.id as url %}
		{% include "maker/widgets/app.html" with clickable=True url=url width=6 %}
	{% endfor %}
	{% else %}
	<div class="mdl-grid mdl-grid--no-spacing rm-form">
		<div class="rm-repo-apps-empty-add mdl-cell mdl-cell--6-col">
			<!-- TODO: Make this a drag and drop area -->
			<i class="rm-repo-apps-empty-add-icon material-icons">file_upload</i>
			<div class="rm-repo-apps-empty-add-title">{% trans 'Add files' %}</div>
			<!-- TODO: Make this translatable properly -->
			<!--
			<div class="rm-repo-apps-empty-add-description-first">
				{% trans 'Drag and drop .apk, .pdf, .epub, videos, photos or music files' %}
			</div>
			-->
			<div class="rm-repo-apps-empty-add-description-second">
				<!--{% trans 'or' %}-->
				<form action="{% url 'apk_upload' repo.id %}" enctype="multipart/form-data" method="post">
					{% csrf_token %}
					<label for="id_file" class="rm-repo-apps-empty-add-upload-browse">
						{% trans 'browse to upload' %}
					</label>
					<p>{{ form.file }}</p>
					<button type="submit" class="rm-button--blue mdl-button mdl-js-button">
						{% trans 'Add' %}
					</button>
				</form>
			</div>
		</div>
		<div class="rm-repo-apps-empty-discover mdl-cell mdl-cell--6-col">
			<i class="rm-repo-apps-empty-empty-icon material-icons">explore</i>
			<div class="rm-repo-apps-empty-empty-title">{% trans 'Discover' %}</div>
			<div class="rm-repo-apps-empty-empty-description">{% trans 'Find things to add from other repos' %}</div>
			<a href="{% url 'add_app' repo.id %}" class="rm-repo-apps-empty-empty-add rm-no-underline">
				<button type="button" class="rm-button--blue mdl-button mdl-js-button">
					{% trans 'add from repos' %}
				</button>
			</a>
		</div>
	</div>
	{% if request.POST.search %}
	<div class="rm-no-search-results">
		{% trans 'Your search did not return any results.' %}
	</div>
	{% endif %}
	{% endif %}
</div>

<script type="text/javascript">
	var rmRepoAppsHeaderSearchInput = document.getElementById('rm-repo-apps-header-search-input');
	if (document.getElementById('id_search').value == '') rmRepoAppsHeaderSearchInput.style.display = 'none';
	function toggleSearch() {
		if (rmRepoAppsHeaderSearchInput.style.display == 'none') {
			rmRepoAppsHeaderSearchInput.style.display = 'block';
			return;
		}
		rmRepoAppsHeaderSearchInput.style.display = 'none';
	}
</script>

maker/templates/maker/repo/index/info.html
{% load i18n %}
<div class="rm-grid--center mdl-grid">
	<div class="mdl-cell mdl-cell--6-col">
		<div class="rm-repo-info-header">
			<span class="rm-repo-info-name-container">
				<div class="rm-repo-info-name-header">{%  trans 'Name' %}</div>
				<div class="rm-repo-info-name">{{ repo.name }}</div>
			</span>
			<a href="{% url 'edit_repo' repo.id %}" class="rm-repo-info-edit">
				<button class="mdl-js-button">
					{% trans 'Edit' %}
				</button>
			</a>
		</div>

		<div class="rm-repo-info-description-header">{% trans 'Description' %}</div>
		<p class="rm-repo-info-description">{{ repo.description }}</p>
		<hr class="rm-repo-info-divider"/>

		<div class="rm-repo-info-storage-header">{% trans 'Storage' %}</div>
		{% if storage %}
		<ul class="rm-repo-info-storages">
			{% for storage in storage %}
			<li class="rm-repo-info-storages-item">
				<a href="{{ storage.get_absolute_url }}" class="mdl-list__item-primary-content">
					{% if storage.disabled %}
					<i class="material-icons mdl-list__item-icon ">cloud_off</i>
					{% else %}
					<i class="material-icons mdl-list__item-icon ">cloud</i>
					{% endif %}
					<span>{{ storage.get_name }}</span>
					<span class="mdl-list__item-sub-title">{{ storage }}</span>
				</a>
			</li>
			{% endfor %}
		</ul>
		{% else %}
		<p>
			<b>{% trans 'Attention:' %}</b>
			{% trans 'This repository has no remote storage. Add one to get your repository published.' %}
		</p>
		{% endif %}

		<p>
			<a href="{% url 'storage_ssh_add' repo.id %}" class="rm-repo-info-storage-add-ssh">
				<button class="mdl-js-button">{% trans 'Add SSH Storage' %}</button>
			</a>
			<a href="{% url 'storage_git_add' repo.id %}" class="rm-repo-info-storage-add-git">
				<button class="mdl-js-button">{% trans 'Add Git Storage' %}</button>
			</a>
			<a href="{% url 'storage_s3_add' repo.id %}" class="rm-repo-info-storage-add-as3">
				<button class="mdl-js-button">{% trans 'Add Amazon S3 Storage' %}</button>
			</a>
		</p>
		<hr class="rm-repo-info-divider"/>

		<div class="rm-repo-info-fingerprint-header">{% trans 'Fingerprint' %}</div>
		<div class="rm-repo-info-fingerprint-container">
			<!-- TODO: Use monospace font -->
			<div class="rm-repo-info-fingerprint">{{ repo.get_fingerprint_with_spaces }}
		</div>
		<!-- TODO: Implement "delete repo" button -->
	</div>
</div>

maker/templates/maker/repo/index/share.html
{% load i18n %}
{% load static %}
<div class="rm-repo-share-container">
	<div class="rm-repo-share">
		{% if not repo.last_publication_date %}
		<div class="rm-repo-share-empty">
			{% trans 'Your repo did not get published yet. Do you already have added and enabled a storage?' %}
		</div>
		{% else %}
		<div class="rm-repo-share-general">
			<div class="rm-repo-share-general-text">
				{% blocktrans count app_count=repo.app_set.all.count trimmed %}
				You have  <span>{{ app_count }} app</span> in your repo. Share it!
				{% plural %}
				You have  <span>{{ app_count }} apps</span> in your repo. Share it!
				{% endblocktrans %}
			</div>
			<a href="{{ repo.url }}" class="rm-repo-share-general-view" target="_blank">
				<button class="mdl-js-button">
					{% trans 'view repo' %}
				</button>
			</a>
		</div>

		<div class="rm-repo-share-share-header">{% trans 'share public link' %}</div>
		<div class="rm-repo-share-share">
			<span class="rm-repo-share-share-url">{{ repo.url }}</span>
			<button class="rm-repo-share-share-copy mdl-js-button" onclick="copyLink('{{ repo.get_fingerprint_url }}')">
				{% trans 'copy link' %}
			</button>
		</div>
		<hr class="rm-repo-share-divider"/>

		<div class="rm-repo-share-add-header">{% trans 'add to an android phone' %}</div>
		<div class="rm-repo-share-add">
			<span class="rm-repo-share-add-text">
				{% trans 'To install these apps on your Android phone, add them to F-Droid.' %}<br />
				{% trans 'F-Droid ensures access to secure app updates.' %}
			</span>
			<a href="{{ repo.url }}/qr_code.html" class="rm-repo-share-add-scan" target="_blank">
				<button class="mdl-js-button">
					{% trans 'Scan QR' %}
				</button>
			</a>
		</div>
		<hr class="rm-repo-share-divider"/>
		<div class="rm-repo-share-social">
			{% blocktrans with name=repo.name asvar text trimmed %}
			Check out this F-Droid repo: {{ name }}
			{% endblocktrans %}
			<a href="https://twitter.com/intent/tweet?text={{ text|urlencode }}&url={{ repo.get_fingerprint_url|urlencode }}"
			   target="_blank">
				<img src="{% static 'maker/images/repo_page/twitter.png' %}"/>
			</a>
			<a href="https://www.facebook.com/sharer/sharer.php?u={{ repo.get_fingerprint_url|urlencode }}"
			   target="_blank">
				<img src="{% static 'maker/images/repo_page/facebook.png' %}"/>
			</a>
		</div>
		{% endif %}
	</div>
</div>
<script src="{% static 'maker/js/repo/share.js' %}"></script>